# Generated by Django 3.2 on 2023-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='address')),
                ('postcode', models.CharField(max_length=10, verbose_name='postcode')),
            ],
        ),
    ]
